### ISSUE TITLE
Unable to run on Windows

### ISSUE THREAD

**Issue by pjBooms** [torstenwerner/java-9-no-jar-hell#1]
"gradlew run" issues the following on my Windows machine:

> > Task :run
> Error occurred during initialization of boot layer
> java.nio.file.InvalidPathException: Illegal char <:> at index 48: C:\work\kit\github\java-9-no-jar-hell\build/libs:C:\work\kit\github\java-9-no-jar-hell\shared\
> build/libs
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':run'.
> > Process 'command 'java'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 0s
> 9 actionable tasks: 1 executed, 8 up-to-date

Do you know what could go wrong?

**Comment by torstenwerner** [comment]
pull request merged
